version: '2.1'
orbs:
  terraform: circleci/terraform@1.2.1
workflows:
create_property:
  jobs:
  - terraform/validate:
      checkout: true
      context: terraform
  - terraform/plan:
      checkout: true
      context: terraform
      persist-workspace: true
      requires:
      - terraform/validate