version: 2.1
orbs:
  terraform: circleci/terraform@3.0.1
workflows:
    example-workflow:
      jobs:
        - terraform/init:
            checkout: true
            context: terraform
        - terraform/validate:
            checkout: true
            context: terraform
