group_name             = "To be deleted"
contract_id            = "ctr_M-1YX7F61"
product_id             = "prd_SPM"
ip_behavior            = "IPV6_COMPLIANCE"
edgeHostname           = "www.lakhanis.net.edgekey.net"
certificate            = 124434
cert_provisioning_type = "CPS_MANAGED"
cnameFrom              = "www.lakhanis.net"
contact                = ["nlakhani@akamai.com"]