variable "group_name" {}
variable "contract_id" {}
variable "product_id" {}
variable "ip_behavior" {}
variable "edgeHostname" {}
variable "certificate" {}
variable "cert_provisioning_type" {}
variable "hostname" {}
variable "contact" {}
variable "rule_format" {}
variable "origin_hostname" {}
variable "configuration_name" {}
variable "cpcode_name" {}